- hosts: localhost
  vars_files:
    - vars/main.yaml
    - vars/diva.yaml
  tasks:
    - include_tasks: common.yaml

    - name: register GATK to copy it into your conda environment.
      shell: "source activate {{ project_name }}; gatk-register {{ gatk_path }}"